version: "3.8"

services:
  database:
    container_name: jk-webpage-database
    image: mysql:8.0.30
    restart: always
    environment:
      - MYSQL_DATABASE=jk-webpage-db
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_TCP_PORT=3307
    ports:
      - '3307:3307'
    volumes:
      - database:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
  app:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    container_name: jk-webpage-backend
    environment:
      - NODE_ENV=dev
      - DB_HOST=database
      - DB_PORT=3307
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=jk-webpage-db
      - APP_PORT=8000
      - ORIGIN_URL=http://localhost:3000
      - WATCHPACK_POLLING=true
    depends_on:
      - database
    command: sh -c './wait-for database:3307 -- npm run dev'
    links:
      - database
volumes:
  database:

